export const workout = [
    { "label": "Aerobic", "value": "Aerobic", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Balance exercises", "value": "Balance exercises", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Barre", "value": "Barre", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Calisthenics", "value": "Calisthenics", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Cardio", "value": "Cardio", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Cross-training", "value": "Cross-training", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Cycling", "value": "Cycling", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Dance", "value": "Dance", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Flexibility Training", "value": "Flexibility Training", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Pilates", "value": "Pilates", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Rowing", "value": "Rowing", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Strength Training", "value": "Strength Training", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Stretching", "value": "Stretching", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Swimming", "value": "Swimming", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Walking", "value": "Walking", onSelect(e: Event) { e.preventDefault() } },
    { "label": "Yoga", "value": "Yoga", onSelect(e: Event) { e.preventDefault() } }
];

export const selection_book_kinds = [
    { label: 'Audiobook', value: 'Audiobook' },
    { label: 'Ebook', value: 'Ebook' },
    { label: 'Printed', value: 'Printed' }
];

export const selection_save = [
    { label: 'No', value: false },
    { label: 'Save', value: true },
];

export const mood = [
    { label: "Neutral", value: "Neutral" },
    { label: "Happy", value: "Happy" },
    { label: "Calm", value: "Calm" },
    { label: "Sad", value: "Sad" },
    { label: "Grateful", value: "Grateful" },
    { label: "Anxious", value: "Anxious" },
    { label: "Angry", value: "Angry" }
]

export const book_of_bible = [
    { "book": "Genesis" },
    { "book": "Exodus" },
    { "book": "Leviticus" },
    { "book": "Numbers" },
    { "book": "Deuteronomy" },
    { "book": "Joshua" },
    { "book": "Judges" },
    { "book": "Ruth" },
    { "book": "1 Samuel" },
    { "book": "2 Samuel" },
    { "book": "1 Kings" },
    { "book": "2 Kings" },
    { "book": "1 Chronicles" },
    { "book": "2 Chronicles" },
    { "book": "Ezra" },
    { "book": "Nehemiah" },
    { "book": "Esther" },
    { "book": "Psalms" },
    { "book": "Proverbs" },
    { "book": "Ecclesiastes" },
    { "book": "Song of Songs" },
    { "book": "Isaiah" },
    { "book": "Jeremiah" },
    { "book": "Lamentations" },
    { "book": "Ezekiel" },
    { "book": "Daniel" },
    { "book": "Hosea" },
    { "book": "Joel" },
    { "book": "Amos" },
    { "book": "Obadiah" },
    { "book": "Jonah" },
    { "book": "Micah" },
    { "book": "Nahum" },
    { "book": "Habakkuk" },
    { "book": "Zephaniah" },
    { "book": "Haggai" },
    { "book": "Zechariah" },
    { "book": "Malachi" },
    { "book": "Matthew" },
    { "book": "Mark" },
    { "book": "Luke" },
    { "book": "John" },
    { "book": "Acts" },
    { "book": "Romans" },
    { "book": "1 Corinthians" },
    { "book": "2 Corinthians" },
    { "book": "Galatians" },
    { "book": "Ephesians" },
    { "book": "Philippians" },
    { "book": "Colossians" },
    { "book": "1 Thessalonians" },
    { "book": "2 Thessalonians" },
    { "book": "1 Timothy" },
    { "book": "2 Timothy" },
    { "book": "Titus" },
    { "book": "Philemon" },
    { "book": "Hebrews" },
    { "book": "James" },
    { "book": "1 Peter" },
    { "book": "2 Peter" },
    { "book": "1 John" },
    { "book": "2 John" },
    { "book": "3 John" },
    { "book": "Jude" },
    { "book": "Revelation" }
]